
exp_dir: not_set
exp_name: exp_1
phase: eval
stage: pos
model: stanza
tagging_settings:
  input_file: not_set
  pretagged: no
evaluation_settings:
  pred_file: not_set
  gold_file: not_set
  # add split by type of tagging
  train_result: 97.52
  train_ufeats: 93.11

